[secrets]
CLIENT_ID = "TY7scMjvrd32wHZSImHtwy334aHp6282iQqysouK"
CLIENT_SECRET = "kY0t77Dwfl1PXnDst0bKcEyjKciWMFeNsksuvjqvjwFcsMmtsPl0yd5q5nYCKRDtxdbZBTnqnGizf8w8J8PHqE4rJDj1hQApTDEzdF1BB7Ab05evGZ548UgvMBwzKpD9"

